config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :todolists do
    member do
      patch :complete
    end
  end
  
  root "todolists#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todolist.rb
class Todolist < ApplicationRecord
  validates_presence_of :name, :due_date
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todolists_controller.rb
class TodolistsController < ApplicationController
  before_action :set_todolist, only: [:show, :edit, :update, :destroy, :complete]

  def index
    @todolists = Todolist.all
  end

  def new
    @todolist = Todolist.new
  end

  def create
    @todolist = Todolist.new(todolist_params)
    if @todolist.save
      redirect_to todolists_path
      flash[:notice] = "Todo List was created"
    else
      render :new
      flash[:notice] = "Todo List was not created"
    end
  end

  def update
    if @todolist.update(todolist_params)
      redirect_to todolist_path(@todolist)
      flash[:notice] = "Todo List was updated"
    else
      render :edit
      flash[:notice] = "Todo List was not updated"
    end
  end

  def destroy
    @todolist.destroy
    redirect_to todolists_path
  end

  def complete
    if @todolist.completed == false
      @todolist.update_attribute(:completed, true)
    else
      @todolist.update_attribute(:completed, false)
    end
    redirect_to todolists_path
  end

  private

  def todolist_params
    params.require(:todolist).permit(:name, :due_date, :note)
  end

  def set_todolist
    @todolist = Todolist.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todolists_helper.rb
module TodolistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todolists/_form.html.erb
<% if @todolist.errors.any? %>
  <h2>error!</h2>
  <ul>
    <%= @todolist.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

<div class="container">
  <%= form_for @todolist do |f| %>
    <div class="form-group">
      <%= f.label :name, "Title" %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :due_date, "Due Date" %>
      <%= f.text_field :due_date, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :note, "Note" %>
      <%= f.text_area :note, class: "form-control" %>
    </div>

    <%= f.submit %>
  <% end %>
</div>

app/views/todolists/edit.html.erb
<%= render partial: "form" %>

app/views/todolists/index.html.erb
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Status</th>
      <th scope="col">Item</th>
      <th scope="col">Due Date</th>
      <th scope="col">Note</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
    </tr>
  </thead>
  <tbody>
    <% count=0 %>
    <% @todolists.each do |todolist| %>
      <tr>
        <th scope="row"><%= count+=1 %></th>
        <td>
          <% if todolist.completed %>
            <%= link_to complete_todolist_path(todolist), method: :patch do %>
              <span class="glyphicon glyphicon-check"></span>
            <% end %>
          <% else %>
            <%= link_to complete_todolist_path(todolist), method: :patch do %>
              <span class="glyphicon glyphicon-unchecked"></span>
            <% end %>
          <% end %>
        </td>
        <td><%= todolist.name %></td>
        <td><%= todolist.due_date %></td>
        <td>
          <%= link_to todolist_path(todolist) do %>
            <span class="glyphicon glyphicon-eye-open"></span>
          <% end %>
        </td>
        <td>
          <%= link_to edit_todolist_path(todolist) do %>
            <span class="glyphicon glyphicon-edit"></span>
          <% end %>
        </td>
        <% if Time.now.to_date <= todolist.due_date %>
          <td>
            <%= link_to todolist_path(todolist), method: :delete, :data => {confirm:"Are you sure?"} do %>
              <span class="glyphicon glyphicon-trash"></span>
            <% end %>
          </td>
        <% else %>
          <td>Expired</td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<button type="button">
  <%= link_to 'New Item', new_todolist_path, class: 'btn btn-secondary' %>
</button>

app/views/todolists/new.html.erb
<%= render partial: "form" %>

app/views/todolists/show.html.erb
<div class="container">
  <table class="table table-striped">
    <tr><th>Title</th><td><%= @todolist.name %></td></tr>
    <tr><th>Due Date</th><td><%= @todolist.due_date %></td></tr>
    <tr><th>Note</th><td><%= @todolist.note %></td>
    </tr>
  </table>

  <button type="button">
    <%= link_to 'Back to index', todolists_path, class: 'btn btn-secondary' %>
  </button>
</div>